[package]
name = "widgets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vendored = [
    "wx-base/vendored",
    "wx/vendored",
    "dep:wx-universal-apple-darwin",
    "dep:wx-x86_64-pc-windows-gnu",
    "dep:wx-x86_64-pc-windows-msvc",
]

[target.'cfg(target_os = "macos")'.dependencies]
wx-universal-apple-darwin = { git = "https://github.com/ancwrd1/wx-universal-apple-darwin", optional = true }

[target.x86_64-pc-windows-gnu.dependencies]
wx-x86_64-pc-windows-gnu = { git = "https://github.com/ancwrd1/wx-x86_64-pc-windows-gnu", optional = true }

[target.x86_64-pc-windows-msvc.dependencies]
wx-x86_64-pc-windows-msvc = { git = "https://github.com/kenz-gelsoft/wx-x86_64-pc-windows-msvc", optional = true }

[dependencies]
regex = "1.5"
wx-base = { path = "../../wx-base", package="wxrust-base" }
wx = { path = "../../wx-core", package="wxrust" }
